version: '3.0'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    env_file:
      - './news_django/.env'
    ports:
      - "5432:5432"
volumes:
  pgdata: