# Generated by Django 4.0.4 on 2022-06-30 22:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 22, 31, 10, 649495, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_edit_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 22, 31, 10, 649495, tzinfo=utc)),
        ),
    ]
