# Generated by Django 4.0.4 on 2022-07-04 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=250)),
                ('company', models.CharField(default='', max_length=250)),
                ('websites', models.CharField(default='', max_length=1000)),
                ('mobile', models.CharField(default='', max_length=50)),
                ('balance', models.FloatField(default=0.0)),
                ('total_gained', models.FloatField(default=0.0)),
                ('total_withdraw', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
