# Generated by Django 4.0.4 on 2022-05-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='test_filed',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='city',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='company',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='mobile',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='total_gained',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='total_withdraw',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='websites',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
