# Generated by Django 4.0.4 on 2022-07-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activateduser',
            name='code_valid_until',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='resetpasswordcode',
            name='valid_until',
            field=models.DateTimeField(),
        ),
    ]
