# Generated by Django 4.0.4 on 2022-05-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0002_remove_extendeduser_test_filed_extendeduser_balance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
