# Generated by Django 4.0.4 on 2022-05-26 20:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorize', '0003_delete_extendeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivatedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=200)),
                ('activated', models.BooleanField(default=False)),
                ('valid_until', models.DateTimeField(default=datetime.datetime(2022, 5, 27, 2, 12, 31, 249895))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
