# Generated by Django 4.0.4 on 2022-05-30 00:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorize', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='activateduser',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 0, 39, 28, 325889, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activateduser',
            name='verification_code',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='ResetPasswordCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
                ('valid_until', models.DateTimeField(default=datetime.datetime(2022, 5, 30, 0, 39, 28, 325889, tzinfo=utc))),
                ('activated', models.BooleanField(default=False)),
                ('activated_on', models.DateTimeField(blank=True, null=True)),
                ('previous_password', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorize.previouspassword')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
