# Generated by Django 4.0.4 on 2022-05-30 00:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorize', '0006_alter_activateduser_valid_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activateduser',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 0, 41, 22, 641870, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resetpasswordcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resetpasswordcode',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 0, 41, 22, 641870, tzinfo=utc)),
        ),
    ]
