# Generated by Django 4.0.4 on 2022-06-01 22:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0008_alter_activateduser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activateduser',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='activateduser',
            name='code_valid_until',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 22, 50, 4, 284668, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resetpasswordcode',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 22, 50, 4, 284668, tzinfo=utc)),
        ),
    ]
