# Generated by Django 4.0.4 on 2022-06-30 22:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0010_alter_activateduser_code_valid_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activateduser',
            name='code_valid_until',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 23, 1, 10, 652284, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resetpasswordcode',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 23, 1, 10, 652284, tzinfo=utc)),
        ),
    ]
